### ISSUE TITLE
node: validating semv

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#408]
regarding this message:

https://github.com/celestiaorg/celestia-node/pull/2477#discussion_r1263438588

- clone repo
- checkout
- build container
- deploy it to robusta-torch-1 (@jrmanes test env) - *it's okay if we break it*

**Comment by jrmanes** [comment]
crashing... :S

```log
---------------------------------------------------
Checking if the keys already exists... 🔐
---------------------------------------------------
Starting the Celestia Node...
---------------------------------------------------


WARNING: Celestia custom network specified. Only use this option if the node is freshly created and initialized.
**DO NOT** run a custom network over an already-existing node store!

2023-07-14T09:01:14.948Z	INFO	node	nodebuilder/module.go:22	Accessing keyring...
2023-07-14T09:01:14.957Z	INFO	module/state	state/keyring.go:40	constructed keyring signer	{"backend": "test", "path": "/home/celestia/keys", "key name": "my_celes_key", "chain-id": "robusta-torch-1"}
2023-07-14T09:01:14.958Z	WARN	module/gateway	gateway/module.go:25	Gateway is enabled, however gateway endpoints are not authenticated. Use with caution!
2023-07-14T09:01:14.962Z	INFO	badger	v2@v2.2007.4/levels.go:183	All 0 tables opened in 0s

2023-07-14T09:01:14.968Z	INFO	badger	v2@v2.2007.4/value.go:1158	Replaying file id: 0 at offset: 0

2023-07-14T09:01:14.969Z	INFO	badger	v2@v2.2007.4/value.go:1178	Replay took: 44.724µs

2023/07/14 09:01:14 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2023-07-14T09:01:14.998Z	INFO	fraudserv	fraudserv/helpers.go:29	joining topic	{"id": "/robusta-torch-1/fraud-sub/badencoding/v0.0.1"}
2023-07-14T09:01:14.999Z	INFO	fraudserv	fraudserv/service.go:97	starting fraud proof service	{"protocol ID": "/robusta-torch-1/fraud/v0.0.1"}
panic: mismatch between data hash commitment from core header and computed data root at height 1: data hash: 3D96B7D238E7E0456F6AF8E7CDF0A67BD6CF9C2089ECB559C659DCAA1F880353, computed root: 257760461993F8F197B421EC7435F3C36C3734923E3DA9A42DC73B05F07B3D08

goroutine 515 [running]:
github.com/celestiaorg/celestia-node/header.(*ExtendedHeader).Validate(0xc000001680)
	/src/header/header.go:137 +0x99b
github.com/celestiaorg/celestia-node/header.MakeExtendedHeader({0x0?, 0x0?}, 0xc000f4ba08, 0xc001cc1000, 0xc000721200, 0x0)
	/src/header/header.go:91 +0x27e
github.com/celestiaorg/celestia-node/core.(*Exchange).Get(0xc002120d08, {0x371cdf0, 0xc0007201b0}, {0xc00211c480, 0x20, 0x40})
	/src/core/exchange.go:113 +0x40f
github.com/celestiaorg/go-header/store.Init[...]({0x371cdf0?, 0xc0007201b0}, {0x37333f8, 0xc000fd1c80}, {0x7fb3ff5a3b80, 0xc002120d08}, {0xc00211c480, 0x20, 0x40})
	/go/pkg/mod/github.com/celestiaorg/go-header@v0.2.7/store/init.go:17 +0xc2
github.com/celestiaorg/celestia-node/nodebuilder/header.newInitStore.func1({0x371cdf0?, 0xc0007201b0?})
	/src/nodebuilder/header/constructors.go:104 +0x5a
go.uber.org/fx/internal/lifecycle.(*Lifecycle).runStartHook(0xc002132460, {0x371cdf0, 0xc0007201b0}, {0xc000fdbc80, 0x0, {0x0, 0x0}, {0x0, 0x0}, {{0xc0005b2eb0, ...}, ...}})
	/go/pkg/mod/go.uber.org/fx@v1.19.3/internal/lifecycle/lifecycle.go:256 +0x212
go.uber.org/fx/internal/lifecycle.(*Lifecycle).Start(0xc002132460, {0x371cdf0, 0xc0007201b0})
	/go/pkg/mod/go.uber.org/fx@v1.19.3/internal/lifecycle/lifecycle.go:216 +0x4c8
go.uber.org/fx.(*App).start.func1({0x371cdf0, 0xc0007201b0})
	/go/pkg/mod/go.uber.org/fx@v1.19.3/app.go:679 +0x3c
go.uber.org/fx.(*App).withRollback(0xc001e82e10, {0x371cdf0, 0xc0007201b0}, 0x0?)
	/go/pkg/mod/go.uber.org/fx@v1.19.3/app.go:661 +0x38
go.uber.org/fx.(*App).start(0x0?, {0x371cdf0?, 0xc0007201b0?})
	/go/pkg/mod/go.uber.org/fx@v1.19.3/app.go:678 +0x3f
go.uber.org/fx.withTimeout.func1()
	/go/pkg/mod/go.uber.org/fx@v1.19.3/app.go:782 +0x85
created by go.uber.org/fx.withTimeout
	/go/pkg/mod/go.uber.org/fx@v1.19.3/app.go:770 +0xea

````

**Comment by jrmanes** [comment]
fixed

**Comment by jrmanes** [comment]
not the expected service name:


![Image](https://github.com/celestiaorg/devops/assets/32740567/3f308d89-3031-44bf-a368-df59ecb92c4b)

**Comment by jrmanes** [comment]
it was solved in this PR:
https://github.com/celestiaorg/celestia-node/pull/2477

here's how it looks like now: https://github.com/celestiaorg/celestia-node/pull/2477#issuecomment-1635981108
